services:
  db:
    image: mongo:latest
    container_name: dontchat-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dontchat
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: './server'
    container_name: dontchat-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      CONNECTION_STRING_URI: mongodb://db:27017/dontchat
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - db

  client:
    build:
      context: ./client
    container_name: dontchat-client
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000

volumes:
  mongo-data:
